# Generated by Django 5.1.4 on 2024-12-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
