export const GET_PROPERTIES_REQUEST: 'GET_PROPERTIES_REQUEST' = 'GET_PROPERTIES_REQUEST';
export const GET_PROPERTIES_SUCCESS: 'GET_PROPERTIES_SUCCESS' = 'GET_PROPERTIES_SUCCESS';
export const GET_PROPERTIES_FAILED: 'GET_PROPERTIES_FAILED' = 'GET_PROPERTIES_FAILED';

export const GET_PROPERTY_REQUEST: 'GET_PROPERTY_REQUEST' = 'GET_PROPERTY_REQUEST';
export const GET_PROPERTY_SUCCESS: 'GET_PROPERTY_SUCCESS' = 'GET_PROPERTY_SUCCESS';
export const GET_PROPERTY_FAILED: 'GET_PROPERTY_FAILED' = 'GET_PROPERTY_FAILED';

export const POST_PROPERTY_REQUEST: 'POST_PROPERTY_REQUEST' = 'POST_PROPERTY_REQUEST';
export const POST_PROPERTY_SUCCESS: 'POST_PROPERTY_SUCCESS' = 'POST_PROPERTY_SUCCESS';
export const POST_PROPERTY_FAILED: 'POST_PROPERTY_FAILED' = 'POST_PROPERTY_FAILED';


export const CLEAR_PROPERTIES: 'CLEAR_PROPERTIES' = 'CLEAR_PROPERTIES';
