export const GET_REQUESTS_REQUEST: 'GET_REQUESTS_REQUEST' = 'GET_REQUESTS_REQUEST';
export const GET_REQUESTS_SUCCESS: 'GET_REQUESTS_SUCCESS' = 'GET_REQUESTS_SUCCESS';
export const GET_REQUESTS_FAILED: 'GET_REQUESTS_FAILED' = 'GET_REQUESTS_FAILED';

export const GET_REQUEST_REQUEST: 'GET_REQUEST_REQUEST' = 'GET_REQUEST_REQUEST';
export const GET_REQUEST_SUCCESS: 'GET_REQUEST_SUCCESS' = 'GET_REQUEST_SUCCESS';
export const GET_REQUEST_FAILED: 'GET_REQUEST_FAILED' = 'GET_REQUEST_FAILED';

export const POST_REQUEST_REQUEST: 'POST_REQUEST_REQUEST' = 'POST_REQUEST_REQUEST';
export const POST_REQUEST_SUCCESS: 'POST_REQUEST_SUCCESS' = 'POST_REQUEST_SUCCESS';
export const POST_REQUEST_FAILED: 'POST_REQUEST_FAILED' = 'POST_REQUEST_FAILED';

export const UPDATE_REQUEST_REQUEST: 'UPDATE_REQUEST_REQUEST' = 'UPDATE_REQUEST_REQUEST';
export const UPDATE_REQUEST_SUCCESS: 'UPDATE_REQUEST_SUCCESS' = 'UPDATE_REQUEST_SUCCESS';
export const UPDATE_REQUEST_FAILED: 'UPDATE_REQUEST_FAILED' = 'UPDATE_REQUEST_FAILED';


export const CLEAR_REQUESTS: 'CLEAR_REQUESTS' = 'CLEAR_REQUESTS';
