export const GET_BANKS_REQUEST: 'GET_BANKS_REQUEST' = 'GET_BANKS_REQUEST';
export const GET_BANKS_SUCCESS: 'GET_BANKS_SUCCESS' = 'GET_BANKS_SUCCESS';
export const GET_BANKS_FAILED: 'GET_BANKS_FAILED' = 'GET_BANKS_FAILED';

// export const GET_PROPERTY_REQUEST: 'GET_PROPERTY_REQUEST' = 'GET_PROPERTY_REQUEST';
// export const GET_PROPERTY_SUCCESS: 'GET_PROPERTY_SUCCESS' = 'GET_PROPERTY_SUCCESS';
// export const GET_PROPERTY_FAILED: 'GET_PROPERTY_FAILED' = 'GET_PROPERTY_FAILED';

// export const POST_PROPERTY_REQUEST: 'POST_PROPERTY_REQUEST' = 'POST_PROPERTY_REQUEST';
// export const POST_PROPERTY_SUCCESS: 'POST_PROPERTY_SUCCESS' = 'POST_PROPERTY_SUCCESS';
// export const POST_PROPERTY_FAILED: 'POST_PROPERTY_FAILED' = 'POST_PROPERTY_FAILED';


// export const CLEAR_BANKS: 'CLEAR_BANKS' = 'CLEAR_BANKS';
