export const GET_NOTIFICATIONS_REQUEST: 'GET_NOTIFICATIONS_REQUEST' = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS' = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILED: 'GET_NOTIFICATIONS_FAILED' = 'GET_NOTIFICATIONS_FAILED';

export const POST_NOTIFICATION_REQUEST: 'POST_NOTIFICATION_REQUEST' = 'POST_NOTIFICATION_REQUEST';
export const POST_NOTIFICATION_SUCCESS: 'POST_NOTIFICATION_SUCCESS' = 'POST_NOTIFICATION_SUCCESS';
export const POST_NOTIFICATION_FAILED: 'POST_NOTIFICATION_FAILED' = 'POST_NOTIFICATION_FAILED';

